<?php

// Plugin definition
$plugin = array(
    'title' => t('DI2D Double R C R 9 3 Wide'),
    'icon' => 'di2d-double.png',
    'category' => t('DI2D'),
    'theme' => 'di2d_double_rcr_9_3_w',
    'regions' => array(
        'section1-row' => t('Section One Row'),
        'section1-column1' => t('Section One First Column'),
        'section1-column2' => t('Section One Second Column'),
        'section2-row' => t('Section Two Row'),
    ),
);
