<?php

// Plugin definition
$plugin = array(
    'title' => t('DI2D Double RCRCRCRC 6 6'),
    'icon' => 'di2d-double.png',
    'category' => t('DI2D'),
    'theme' => 'di2d_double',
    'regions' => array(
        'section1-row' => t('Section One Row'),
        'section1-column1' => t('Section One First Column'),
        'section1-column2' => t('Section One Second Column'),
        'section2-row' => t('Section Two Row'),
        'section2-column1' => t('Section Two First Column'),
        'section2-column2' => t('Section Two Second Column'),
        'section3-row' => t('Section Three Row'),
        'section3-column1' => t('Section Three First Column'),
        'section3-column2' => t('section Three Second Column'),
        'section4-row' => t('Section Four Row'),
        'section4-column1' => t('Section Four First Column'),
        'section4-column2' => t('Section Four Second Column'),
    ),
);
