<?php

/**
 * Implements hook_ctools_plugin_directory()
 */
function di2d_panels_bootstrap_ctools_plugin_directory($module, $plugin) {
  if ($module == "panels" && in_array($plugin, array('layouts', 'styles', 'content_types'))) {
    return "plugins/$plugin";
  }

  if ($module == "ctools" && in_array($plugin, array('content_types'))) {
    return "plugins/$plugin";
  }
}

function di2d_panels_bootstrap_theme() {
  $theme = array();

  $theme['bootstrap_main_menu'] = array(
      'variables' => array(
          'items' => array(),
      ),
      'path' => drupal_get_path('module', 'di2d_panels_bootstrap') . '/theme',
      'template' => 'bootstrap-main-menu',
  );
  return $theme;
}
